### ISSUE TITLE
Accept empty distance parameter

### ISSUE THREAD

**Issue by jkreft-usgs** [ACWI-SSWD/nldi-services#110]
If there is an empty distance parameter, the distance parameter returns an error which is not what we actually want to do- it should just ignore the distance parameter. https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-05429700/navigate/UM?distance=

**Comment by kkehl-usgs** [comment]
https://github.com/ACWI-SSWD/nldi-services/pull/142

**Comment by kkehl-usgs** [comment]
What is the maximum number of kilometers we should support for distance?   Is 9999 kilometers okay?

**Comment by dblodgett-usgs** [comment]
Seems like a fine maximum. Seeing as the Mississippi is only about 3700km, it will ensure we can get the biggest river the system should deal with ;)

**Comment by kkehl-usgs** [comment]
This change was implemented and merged.

**Comment by dblodgett-usgs** [comment]
I'm still getting an error for an empty distance parameter... `https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-05429700/navigate/DM/nwissite?distance=`

**Comment by dblodgett-usgs** [comment]
Looks good. 
`https://labs-dev.wma.chs.usgs.gov/api/nldi/linked-data/nwissite/USGS-05429700/navigate/DM/nwissite?distance=1`

Returns one site.

`https://labs-dev.wma.chs.usgs.gov/api/nldi/linked-data/nwissite/USGS-05429700/navigate/DM/nwissite?distance=`

Returns all the sites.
