### ISSUE TITLE
Feature-collection view of NLDI features.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#133]
We need a "catalog view" of NLDI features (OGC-API Features) 
e.g. https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/ should return a GeoJSON feature collection of the nwissites. 

This end point should implement that same behavior as the items end point of OGC-API Features. http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_items_

**Comment by kkehl-usgs** [comment]
https://github.com/ACWI-SSWD/nldi-services/pull/144

**Comment by dblodgett-usgs** [comment]
Works -- I'm happy.
