### ISSUE TITLE
update from springfox to springdoc and openAPI3

### ISSUE THREAD

**Issue by jkreft-usgs** [ACWI-SSWD/nldi-services#143]
Springfox is dying a slow death.  The [springdoc project](https://springdoc.org/)is what other public-facing spring projects are using at the WMA, and we should probably join them.

**Comment by dblodgett-usgs** [comment]
Is this something that makes sense to add to the V milestone / next release cc: @dsteinich and @kkehl-usgs ?

**Comment by kkehl-usgs** [comment]
Dave mentioned he would like it to happen soon.  I think it makes sense to add it.

**Comment by dblodgett-usgs** [comment]
Does #153 get this issue taken care of?

**Comment by kkehl-usgs** [comment]
Yes, #153 should resolve this.  Once deployed to the test server, the user ought to be able to input the URL as .../nldi/swagger and be redirected to the swagger page.

**Comment by dblodgett-usgs** [comment]
https://labs-dev.wma.chs.usgs.gov/api/nldi/swagger Looks like this is all good!
