### ISSUE TITLE
Migrate NLDI to use stronger database.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#158]
In conversation with @jkreft-usgs, we agreed that the NLDI should be moved to the same database used by some other production projects in waterdata.usgs.gov. Not really an issue for the code in this repository, but I want to keep the work associated with this milestone in one place for the community's awareness.

**Comment by jkreft-usgs** [comment]
we may be able to survive on this for the moment

**Comment by dblodgett-usgs** [comment]
I agree. Based on the fix to that index, I think we should hold off on doing this.
