### ISSUE TITLE
clean up demo page

### ISSUE THREAD

**Issue by jkreft-usgs** [ACWI-SSWD/nldi-services#16]
http://cida.usgs.gov/nldi/demo

is pretty much hacked together.  We should clean it up a bit

**Comment by dblodgett-usgs** [comment]
The short version is: https://cida.usgs.gov/nldi/about/demo
has code here: https://github.com/ACWI-SSWD/nldi-services/blob/master/src/main/webapp/WEB-INF/views/demo.jsp
There's another NLDI client here: https://www.waterqualitydata.us/portal/
That Jim can get you to the source for.
We want to add some of the functionality from the water quality portal client to the basic "demo" client.
 Sent at 3:34 PM on Thursday
 me:  The functionality to add is the map layers that you click in the WQP to populate source/identifier  in the demo app
If you look at the demo app -- you'll see the first pull down has three options. Choosing one of those would turn on a map layer that you would click to get the id to go in the identifier box.

**Comment by dblodgett-usgs** [comment]
I'm going to close this for now. I'm not really sure this demo client is necessary with some of the other stuff that's available. The client was built as a development aid -- any additions to it should be for that purpose, IMHO.

**Comment by dblodgett-usgs** [comment]
Greg has a demo app basically done from some previous work. Wondering if it's worth getting that in as a demo given that we have it.

**Comment by jkreft-usgs** [comment]
Lets put it in here: https://labs.waterdata.usgs.gov/about-nldi/index.html
https://github.com/usgs/waterdata_labs/blob/master/content/nldi.md

That page could use some clean-up anyways.

**Comment by dblodgett-usgs** [comment]
I like that idea. I can refresh that page and add some stuff about characteristics as part of #159. Looks like the demo app was pulled out of the repo completely. So should @gpetrochenkov-usgs work on getting the demo app to a place that it could go into this project or are you saying we should we deploy it in the waterdata_labs project?

Guessing we'll want to sync up web-style with the labs project too. @gpetrochenkov-usgs you up to tackle that?

**Comment by jkreft-usgs** [comment]
I think we should drop the demo app into that page in labs, or another, similar page on in the waterdata_labs repo.

**Comment by dblodgett-usgs** [comment]
@gpetrochenkov-usgs -- that work for you?

**Comment by gpetrochenkov-usgs** [comment]
Sure that shouldn't be a problem.  The only work that would be needed is the actual CSS portion may need to be changed.  @jkreft-usgs  If I remember correctly it would need to use the US Web Design System to be on labs.

**Comment by dblodgett-usgs** [comment]
This fell off the table. Should reopen in the context of a new effort.
