### ISSUE TITLE
Refresh crawler code base.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#160]
No functional changes, but the crawler code base has a number of updates pending in open PRs. 

https://github.com/ACWI-SSWD/nldi-crawler/pulls

Should make sure we have the project building and using up-to-date dependencies.

**Comment by kkehl-usgs** [comment]
This one is finished.

**Comment by dblodgett-usgs** [comment]
Build still failing?

**Comment by kkehl-usgs** [comment]
Looks successful now: https://jenkins.wma.chs.usgs.gov/job/IOW/job/IOW-ALLGEMEIN/job/nldi-crawler-build/

**Comment by dblodgett-usgs** [comment]
OK -- should we call this done?

**Comment by kkehl-usgs** [comment]
Yes this is done.
