### ISSUE TITLE
Add option to get back full-resolution basin boundary.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#171]
The current url template is:

`/linked-data/{featureSource}/{featureID}/basin`

We should add a parameter `simplified` which defaults to TRUE. 

If `/linked-data/{featureSource}/{featureID}/basin?simplified=FALSE`

Then we would return the full resolution geometry.

See comments below for more.

**Comment by jkreft-usgs** [comment]
I think we even simplify the `catchmentssp` even more on the way out via a built-in postgis simplification algorithm.

**Comment by dblodgett-usgs** [comment]
There it is. https://github.com/ACWI-SSWD/nldi-services/blob/49f93b8240e4c68d39c1cd6cd32f730a9f05112f/src/main/resources/mybatis/stream.xml#L70

I'll put this into the queue for someone to implement the override.
