### ISSUE TITLE
Error message for distance parameter.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#205]
If the distance parameter isn't included, we should throw a 401 with a little json that says: `invalid request: the distance query parameter is required`

**Comment by EthanGrahn** [comment]
I would suggest using [400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) or [406 Not Acceptable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) to better represent the error.
