### ISSUE TITLE
Distance not handling major/minor paths correctly?

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#36]
@pauldzy - can you clarify the situation here?

**Comment by dsteinich** [comment]
At this time, my vote to is document that a decision was made in all versions of the navigation to base distances on "path length" for performance reasons.

I also tried to use flow line length in the NLDI navigation, but the data processed increased exponentially when navigating multiple divergences.

**Comment by pauldzy** [comment]
Hi folks,

Apologies for taking so long to get this written up.  This is a followup to the NLDI meeting in October.

Navigation on the NHDPlus network is constrained by examination of the Path Length attribute (and in NHDPlus 1.0 could be constrained as well by Path Time).  Path Length is defined as the "distance to the terminal NHDFlowline feature downstream along the main path.".  The key point here is the "along the main path" aspect.  This means that as you move upwards the path lengths for any divergences are always pegged to the path length on the main path.  

Most users notice this when they navigate upstream beginning upon a divergence representing a "shortcut" in comparison to the main path.  Their navigation continues upstream on this shortcut but then they receive confusing results when their navigation should rejoin the main path.

So in this scenario on the Mississippi, a user wishes to navigate upstream from ComID 19085557 which is about 6.5 km to get back onto the main path.
![capture10](https://cloud.githubusercontent.com/assets/4131067/20495561/97bfc588-afef-11e6-88e3-d6a573fc7b67.PNG)

Attempting to go further, say 7.5 km one would expect the results to rejoin the Mississippi and continue but instead the results "pause" at the junction.  
![capture11](https://cloud.githubusercontent.com/assets/4131067/20495624/dd6d3d72-afef-11e6-9556-d07b3466e591.PNG)

The pause remains at 8.5 km (notice the other branches to the upper left are growing as expected).
![capture12](https://cloud.githubusercontent.com/assets/4131067/20495676/0888113a-aff0-11e6-8c88-75613e938602.PNG)

And only around 9.05 km is there movement.  Here is the results at 9.5 km
![capture13](https://cloud.githubusercontent.com/assets/4131067/20495732/4f4344c8-aff0-11e6-8f10-9cf463d05ecf.PNG)

So from here on Navigation continues upstream but while those branches to the upper right are showing 9.5 km, the results that rejoined the Mississippi are short. If we test this using my alternative SDO_NET we get what most users would probably expect.
![capture14](https://cloud.githubusercontent.com/assets/4131067/20495856/d6aa86b0-aff0-11e6-8e34-f0c61670dd9a.PNG)

So to explain what is happening we just need to back up slightly and do things again on the main path.
So let's run upstream about 7.5 km from ComID 19085515 covering again just about the entire length of the shortcut
![capture](https://cloud.githubusercontent.com/assets/4131067/20495099/b7181b44-afed-11e6-8ecd-20859b7896a2.PNG)

As we navigate further upwards the navigation results will just stop at the start of the divergence and "wait" while the main path is traversed.
![capture1](https://cloud.githubusercontent.com/assets/4131067/20495267/5cbdfdac-afee-11e6-82fd-2af860791355.PNG)

Note again the side streams to the upper right continue to produce results.
![capture2](https://cloud.githubusercontent.com/assets/4131067/20495290/75ea911e-afee-11e6-962e-5c14f38ce3ce.PNG)

Until we finally come together and from there everything flows as expected.
![capture4](https://cloud.githubusercontent.com/assets/4131067/20495317/8c64031c-afee-11e6-9e99-dd26071cc5c6.PNG)

So this should show that our navigation on the divergence is tied to navigation on the main path and if the main path is longer, cannot rejoin the main path until the cost of the main path is paid.

This is a known issue with NHDPlus navigation and there is no solution I know of short of determining cost in an alternative manner, such as by geometric distance.  I believe the examples we discussed on the October call originating from large-scale divergences are just extreme examples of the above more simple example.

Paul

**Comment by dblodgett-usgs** [comment]
This is a won't fix for now.
