### ISSUE TITLE
Query by lat/lon location.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#37]
It would be generally useful to be able to query the system by lat/lon. Initially, this would be a point in polygon match to a catchment, long term it could be more sophisticated.

This can be closed when an lat/lon point can be submitted to get a comid or other featuresource id. 

e.g. `.../nldi/{{featuresource}}?lat=40&lon=90` The method of submitting lat/lon can be discussed when the work is planned.

**Comment by kkehl-usgs** [comment]
I was thinking to go through the list of features for a given feature source, and calculate the nearest feature to the point the user specified using the Haversine method, and then return that feature.  Let me know if that is problematical.

**Comment by dblodgett-usgs** [comment]
Since we have the catchment geometry (polygons), you should be able to use [`ST_intersects`](https://postgis.net/docs/ST_Intersects.html) with a submitted point against the nhdplus.nhdcatchmentsp table. The `featureid` column in that table can be joined on the `comid` column in other nldi tables.

**Comment by kkehl-usgs** [comment]
Is it possible to get a 404 if the user enters a latitude and longitude inside the area we have data for?    Or is his point always going to be inside a catchment?

**Comment by dblodgett-usgs** [comment]
The catchment coverage is complete within the bounds of the coastal flowlines. That is, the great lakes and the ocean are excluded. Other large lakes, such as Lake Winnebago and the Great Salt Lake are included in the catchment network.

**Comment by dblodgett-usgs** [comment]
From an email, copying here for posterity.

I did a little hacking around here in a local database.

SELECT featureid
	FROM nhdplus.catchmentsp
	WHERE ST_Intersects(nhdplus.catchmentsp.the_geom,
					    'SRID=4269;POINT(-89.35 43.0864)'::geography);

Gives you back a COMID.

So, I would expect:
http://localhost:8080/nldi/linked-data/comid?lat=43.0864&lon=-89.35

To be the same response data as:
https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/13294318

For now, I’m ok leaving this query at this. That is to say, I think this mostly fits into the Network Controller and NOT the Linked Data Controller. 

Theoretically, we could do the same thing for any of the `{featureSource}` values, but I would expect the behavior to be a bit different and the real value is in this core comid discovery. Lat/lon discovery for point `{featureSource}`s would be an ST_ClosestPoint query and not quite as straight forward as the intersects.

**Comment by kkehl-usgs** [comment]
After discussions with Dave B., this will be implemented in the NetworkController since it applies only to comid as a feature source, and will take the form:

linked-data/comid/position?coords=POINT(x y)

**Comment by kkehl-usgs** [comment]
Actually we can't have whitespace in URLs, so that will be

linked-data/comid/position?coords=POINT(lon,lat)

**Comment by dblodgett-usgs** [comment]
A `,` has a special meaning in WKT -- can we use url escaping on query parameters? 

`linked-data/comid/position?coords=POINT(x%20y)`

**Comment by dblodgett-usgs** [comment]
Looks like we may need a spatial index on the catchmentsp table? I'm getting timeouts to: https://labs-dev.wma.chs.usgs.gov/api/nldi/linked-data/comid/position?f=json&coords=POINT(-89.35%2043.0864)

**Comment by dblodgett-usgs** [comment]
Nice!!
