### ISSUE TITLE
Modify default navigation response and version API.

### ISSUE THREAD

**Issue by dblodgett-usgs** [ACWI-SSWD/nldi-services#50]
For the `...navigate/` we currently return a list of navigation option urls. Each of those urls returns the flowlines for that navigation.

Instead of the flowlines, the navigate methods should return the list of available data sources for that method. e.g. `.../navigate/UT/` should return the list of indexed data sources. `flowlines` should be one of the options in this list.

This change is significant enough that we should version the API, not sure what the versioning scheme should be, but we should maintain the un-versioned API so existing applications continue to function.

This issue can be closed when the NLDI service URL includes a version and each navigation option returns a list of available data sources for that navigation.

**Comment by kkehl-usgs** [comment]
Could you provide sample output for .../navigate/UT?

**Comment by dblodgett-usgs** [comment]
```json
[
  {
    "source": "Flowlines",
    "sourceName": "NHDPlus flowlines",
    "features": "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate/UT/flowline"
  },
  {
    "source": "huc12pp",
    "sourceName": "HUC12 Pour Points",
    "features": "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate/UT/huc12pp"
  },
  {
    "source": "nwissite",
    "sourceName": "NWIS Sites",
    "features": "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate/UT/nwissite"
  },
  {
    "source": "wade",
    "sourceName": "Water Data Exchange 2.0 Sites",
    "features": "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate/UT/wade"
  },
  {
    "source": "WQP",
    "sourceName": "Water Quality Portal",
    "features": "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate/UT/wqp"
  }
]
```

**Comment by kkehl-usgs** [comment]
Any possibility to avoid versioning at this time by creating a new endpoint something like this?

https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-09060799/navigate_options/UT

Versioning has a tendency to become a long-term pain point if done ad hoc.   If we need it now, okay.  If we could defer it, it would be better.

**Comment by dblodgett-usgs** [comment]
In conversations with @kkehl-usgs and @jkreft-usgs -- we decided that adding a version to the API right now is not the right thing. 

Instead, we will add a `.../navigation/` endpoint in addition to the `.../navigate/` endpoint. `.../navigate/` will be deprecated. 

@jkreft-usgs wants to support versioning through API-Gateway in the future but we agreed that it is most expedient to get the non-versioned API out now.

**Comment by dblodgett-usgs** [comment]
Looks good to me!
