### ISSUE TITLE
Simple documentation blurb would be helpful for coordinate system in NLDI

### ISSUE THREAD

**Issue by pauldzy** [ACWI-SSWD/nldi-services#53]
Hello,

This issue is based on an exchange over loading EPA NPDES data into NLDI from early Feb, 2018.  I'll just try to distill it down.

So data goes into NLDI (usually via a crawler) and data comes out of NLDI.  It would clarify this process to document more the expected coordinate system for both ends of the workflow.  From the issue that occurred and Dave's response, NLDI itself does not use any particular coordinate system but generally the expectation is that the data is geodetic in form.  So whether NAD83 or WGS84 or NAD27, its just not that relevant.  Technically I would assume there are no SRID constraints on the internal tables holding program data and no places where PostGIS spatial functions would fail on differing SRIDs.

Yet while nothing is enforced what is the best practice?  I think as the flowlines are stored in NAD83 and currently are returned unchanged as NAD83 that it might be best for NLDI data submitters to utilize a NAD83 cs when submitting data. 

However, with the release of the GeoJSON 2.0 specification users may well expect the NLDI to be WGS84.  I do realize the differences are so small as to be a waste of time to discuss when the data represents water.  

But perhaps then the documentation just says something along those lines whereby you can submit in any geodetic coordinate system but if in doubt or if the idea of this imprecision bothers you then use NAD83.  It would be swell if the crawlers then had a check install to make sure all ordinates lie between the 180s./90s.

Geodetic in and geodetic out.  

Cheers,
Paul

**Comment by dblodgett-usgs** [comment]
Will add some detail about this here: https://github.com/usgs/waterdata_labs/blob/master/content/nldi.md

@kkehl-usgs, @jkreft-usgs could we put some informal documentation in the front matter of: https://labs.waterdata.usgs.gov/api/nldi/swagger-ui.html where would I check that in??

**Comment by jkreft-usgs** [comment]
pull requests are always welcome- that seems like a good spot

**Comment by jkreft-usgs** [comment]
I am working on building an API hub to add additional documentation to what is in swagger

**Comment by kkehl-usgs** [comment]
You can probably put it in ConfigOpenApi.java, after this pull request gets checked in:  https://github.com/ACWI-SSWD/nldi-services/pull/145

**Comment by dblodgett-usgs** [comment]
#145 got merged but I don't see a `ConfigOpenApi.java` -- can you point me to where the text should get checked in?

**Comment by kkehl-usgs** [comment]
https://github.com/ACWI-SSWD/nldi-services/tree/master/src/main/java/gov/usgs/owi/nldi/openapi/ConfigOpenApi.java

Let me run a quick test and see how the text should be formatted and I will give an example here in a little bit.

**Comment by kkehl-usgs** [comment]
Okay, so in ConfigOpenApi.java there is a title and a description.   The text for both can be set to whatever, but they are simple Java strings, so there are no formatting options.    So whatever is put into description will work like a single paragraph.  It will wrap naturally with browser size, but you can't add any line breaks (or html tags).

**Comment by dblodgett-usgs** [comment]
Where will that show up? Looking here: https://labs.waterdata.usgs.gov/api/nldi/swagger-ui.html#/linked-data-controller/getFlowlinesUsingGET

I'd like to be able to add a description to each of these end points. Is that possible in this config?

**Comment by kkehl-usgs** [comment]
Ah, no.  What I was describing was the overall summary at the top of the swagger page.

If you want descriptions for different endpoints, that is probably possible but it would involve adding annotations in the various controllers.  Let me see if I can do it and then I'll add an example here.

**Comment by dblodgett-usgs** [comment]
If this turns into more than a few minutes of work, I think we should punt on adding it in Swagger, but having a clear way to add a textual description to each controller would be nice.

**Comment by kkehl-usgs** [comment]
Okay, so you have to go to each endpoint method you want to document and add something like this at the top of the method:

@Operation(summary = "getFeatures", description = "returns a list of features for a given data source")

So the only trick that is involved is figuring out which method in the java code corresponds to which endpoint in swagger.  Swagger gives you the class names, but not the method names, so you have to look at the unique URLs like 


​/linked-data​/{featureSource}​/{featureID}​/navigate​/{navigationMode}​/{dataSource}

and look them up from there, but it's not too bad.

**Comment by dblodgett-usgs** [comment]
Use back ticks so the github user `@operation` doesn't get tagged. e.g. `@Operation(summary = "getFeatures", description = "returns a list of features for a given data source")`
